services:
  db:
    container_name: db_control_vehicular
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sistemas-internet-31
      MYSQL_ROOT_DATABASE: vehicle_control
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes: ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db-web
  web:
    container_name: web_control_vehicular
    build: ./app
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - db-web
networks:
  db-web:
    driver: bridge
